### ISSUE TITLE
Which license? [You should to set a license]

### ISSUE THREAD

**Issue by Wohlstand** [GhostHawk10/VSMBX-Source#1]
I see than you forgot to put a license file, even it will contain "It's in a public domain!" phrase, but because you are a right holder, you have a choice between various licenses or write your own license yourself.
### Short info about most popular licenses:

**GNU GPLv3**. Most popular license in a free software community. It allows others to use your project with any purposes as-is and allows to taking your source code for other purposes, BUT if your code was used in other project, than project should be in GNU GPLv3 too. Hiding of your source code is forbidden.

**ZLib/MIT/BSD**. Liberal licenses which allows to use your project include code with any purposes even commercial with closing of your code pieces in closed-source code.
## How to add a license

Open your project and click "Add new file":
![-49](https://cloud.githubusercontent.com/assets/6751442/8437317/2c2dd4a2-1f56-11e5-98c8-2b0ad7ff034e.png)

then type "LICENSE" word into file name, and then choice one of exists licenses:
![-50](https://cloud.githubusercontent.com/assets/6751442/8437372/6d61d4d2-1f56-11e5-9fd1-84bb15736e49.png)

...or write your license yourself!

**Comment by aeromatter** [comment]
Thanks for reminding me, the GNU GPL v3.0 license is now added.
